version: "3"
services:
  bot:
    build:
      context: ./src/bot
      dockerfile: Dockerfile-dev
    volumes:
      - ./volumes/bot:/app
      - ./volumes/bot_mod_cache:/go/pkg/mod
    deploy:
      resources:
        limits:
          memory: 1500m